(function(){function loadScript(url,callback){var script=document.createElement("script")
script.type="text/javascript";script.async=!0;if(script.readyState){script.onreadystatechange=function(){if(script.readyState=="loaded"||script.readyState=="complete"){script.onreadystatechange=null;callback()}}}else{script.onload=function(){callback()}}
script.src=url;document.getElementsByTagName("head")[0].appendChild(script)}
loadScript("//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js",function(){$(document).ready(function(){$("#search-icon").click(function(){$(".main-nab").toggleClass("add")});var cds=$('.posi').width();$('.abbe').width(cds);var percent=0;var timer=setInterval(function(){$(".loadinger span").text(percent+"%")
percent+=1;if(percent>100){clearInterval(timer)
$(".manual").remove();function dasi(){$('.another').each(function(was){$(this).addClass("cape-"+(was+1))
$('.suram').each(function(das){var noscriptContents=$($(this).html());$(".cape-"+(das+1)).html(noscriptContents)})})}
dasi();var script=document.createElement("script");script.type="text/javascript";script.src="//rawgit.com/OwlCarousel2/OwlCarousel2/develop/dist/owl.carousel.min.js";document.getElementsByTagName("head")[0].appendChild(script);function oli(){$(".gridItemCard-module_title_27g2e").each(function(d){$(this).addClass("zos-"+(d+1));$(".hanya-post").each(function(w){$(this).addClass("lol-"+(w+1));var hunter=$(".zos-"+(w+1)).attr("href");$(".lol-"+(w+1)).load(hunter+' .postinganku',function(){$(this).text(function(){return $(this).text().substring(0,250)});$(".hanya-post img").remove()})})});$(".posi").each(function(i){$(this).addClass("tukang-"+(i+1));$(".button-module_altPrimary_LUoyu").each(function(s){$(this).click(function(){$(".posi").removeClass("aktif");$(".tukang-"+(s+1)).addClass("aktif")})})});$(".main-gamb").each(function(i){var cos=$(this).attr("main-src");$(this).attr("main-src",function(a,b){return b.replace("s320","s1600")});$(this).attr("src",cos);$(this).attr("src",function(a,b){return b.replace("s320","s1600")})})}
var link=$(".docu").attr('href');$("#subscribe-css").append("<div class='slider'></div>");$(".slider").load(link+' .blog-posts .another',function(){dasi();oli();$(".slider").owlCarousel({items:6,nav:!0,dots:!0,mouseDrag:!0,responsiveClass:!0,responsive:{0:{items:1},480:{items:1},600:{items:2},769:{items:3}}});jQuery('link[rel="shortcut icon"]').attr('href','https://1.bp.blogspot.com/-x4dveXB5tc8/Wy2fMN9ozgI/AAAAAAAABJ0/ZWxOgPDGgfEgT6mEVx1qmR008SM1PZIHwCEwYBhgL/s160/favicon.ico');$(".main-iklan").append('<a href="https://yllix.com/publishers/725353" target="_blank"><img src="//ylx-aff.advertica-cdn.com/pub_c6lers.png" width="728" height="90" border="0" alt="Monetize your website traffic with yX Media" title="Monetize your website traffic with yX Media" /></a>')
$(".slider.owl-loaded.owl-drag").fadeIn("slow");$(".sipanse,#loading,.uil-ripple").fadeOut();$(".pageLoading,.loadie").fadeOut()
$(".abbe").hide();$(".main-gamb,.gridItemCard-module_content_wdidJ,.gridItemCard-module_footer_2eYXU").fadeIn()});oli();dasi()}},0.1)
$(".postinganku li").each(function(dw){$('.postinganku li').each(function(i){$(this).delay((i++)*200).fadeTo(1400,1)}).css("display","block");$('.proka').each(function(i){var hue='rgb('+(Math.floor((256-199)*Math.random())+50)+','+(Math.floor((256-199)*Math.random())+80)+','+(Math.floor((256-199)*Math.random())+100)+')';$(this).css("background-color",hue)})
$(this).prepend("<div class='proka' >"+(dw+1)+"</div>");var hue='rgb('+(Math.floor((256-199)*Math.random())+50)+','+(Math.floor((256-199)*Math.random())+80)+','+(Math.floor((256-199)*Math.random())+100)+')';$(this).css("background-color",hue)})});$("img").attr("src",function(qw,dw){return dw.replace("s320","s1600")})})})()